# Generated by Django 3.0.5 on 2020-05-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PnbPartKeepr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='footprint',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='footprintattachment',
            options={'ordering': ['content']},
        ),
        migrations.AlterModelOptions(
            name='footprintcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='partattachment',
            options={'ordering': ['content']},
        ),
        migrations.AlterModelOptions(
            name='partcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='projectattachment',
            options={'ordering': ['content']},
        ),
        migrations.AlterModelOptions(
            name='stockentry',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='storagelocationcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Bought stock price per part', max_digits=13, null=True),
        ),
    ]
