# SPDX-FileCopyrightText: 2025 Pierre-Noel Bouteville <pnb990@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause
#
---
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/partkeepr.Dockerfile
    environment:
      USER: dev
      DEBUG: 1
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "partkeeprpsqldb"
      DB_USER: "partkeeprpsqluser"
      DB_PASS: "PartKeeprPsqlPass"
      MEDIA_ROOT: "/var/partkeepr/media"
      STATIC_ROOT: "/var/partkeepr/static"
      BACKUP_DIR: "/var/partkeepr/backups"

    ports:
      - "8000:8000"

    volumes:
      - ..:/home/dev/project:cached
      - partkeepr-data:/var/partkeepr

    depends_on:
      db:
        condition: service_healthy
        restart: true

    command: sleep infinity

  db:
    image: postgres:17-trixie
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      DEBUG: 1
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 30
      start_period: 1s

volumes:
  postgres-data:
  partkeepr-data:
